plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'dev.armazi'
version = '1.0.0-BETA'

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://repo.maven.apache.org/maven2' }
    maven { url 'https://jcenter.bintray.com' }
    maven { url 'https://libraries.minecraft.net' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT'
    
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'
    implementation 'net.kyori:adventure-api:4.17.0'
    implementation 'net.kyori:adventure-text-minimessage:4.17.0'
    
    compileOnly 'com.comphenix.protocol:ProtocolLib:5.1.0'
    
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.register('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    from sourceSets.main.output
    
    relocate 'com.zaxxer.hikari', 'dev.armazi.libs.hikari'
    relocate 'com.github.benmanes.caffeine', 'dev.armazi.libs.caffeine'
    
    archiveBaseName = 'ArmaziAntiXray'
    archiveVersion = project.version
    archiveClassifier = null
}

build.dependsOn shadowJar